function [] = myGUI()
S.fh = figure('units','pixels',...
              'position',[500 50 800 700],...
              'menubar','none',...
              'name','GUI_1',...
              'numbertitle','off',...
              'resize','off');
          

S.pb = uicontrol('style','push',...
                 'units','pix',...
                 'position',[10 10 140 30],...
                 'fontsize',14,...
                 'string','RUN',...
                 'callback',{@pb_call,S});
             
S.ax = axes('units','pixels',...
            'position',[400 400 390 290]);

